server:
  port: 80
  max-http-header-size: 10240
  #spring-session-opem: false #是否开辟spring session，如果是多机环境需要开启true/false

beetl:
  #delimiter-statement-start: \@ #开始结束标签(yaml不允许@开头)

  resource-auto-check: true         #热加载beetl模板，开发时候用，上线要改为false

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages  #html路径
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  jta:
    atomikos:
      properties:
        max-actives: -1
  mail:
    host: smtp.qq.com
    port: 587
    username: 270014318@qq.com
    password: zjs715701
    from: 270014318@qq.com

mybatis-plus:
  mapper-locations: classpath*:cn/stylefeng/**/mapping/*.xml  #xml文件加载路径
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true    #缓存开启
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: assign_id
      table-underline: true

log:
  path: _app_logs


order:
  name: 张三
  age: 13
  sex: 男

